def trans(s):
  d = {'C':'G','A':'T','G':'C','T':'A'}
  return d[s]

def reverse_complement(s):
  s = s[::-1]
  return ''.join(map(trans,s))

s1 = 'TATACCCCCATGAAGTGGGGGTGAAAGTAATCTGAAGAAGGTAACCGTCCGTGGCACGGGCACAAGTACTAGTACAATGCGTAGACTTCGTCCCTATCCTGCCGCATTATCCATCCATGTGTGGAGATGGGGAAGATGTTTCGTGGTAGGCGAACGTCGATAGCACGCAGAGTTCGCGTCATATACTGAGCAAAAGAGGGACTCCTCTCGGAGTCTTCAGGCATTCACCCTTACATAATCCCGTTTATTAGGCACTGCGCGTATATCCAGAAGGTTAATCCGACCTCTGGGAGCTATGTCTGACTACTTAACTCTGCATGCTGTTGTCATGTCCTTCACGACTCGAGTAGGGAGTTCTCAGTCTCCAGAGATCAGAGTGAAAATACTACACTTGGCAAGAAGGATTATCCCAACTAAACCGAAGGAATAAGTGTCCGGATACTTGAATCATGGGCGCACCCCCGAGGATGTGGGTGAGCGACGTCGCTCAGTTATACTAATATAGCCCGTTTGACTCATAGACGCCGTCTCGCCTGTCTATAACCATATCAACTCACATCTGTTTAACTGAAAGCCCAGACCAAGACTGTGTCAGTGAGTCCTAACGGGAGGAGATTCTCACGGAGCGAAATTTGCGACTCTCATGAATTGTGTGCGTACTGGCGCTTTGCCTCCCCCCATTTTGTCCTTTGCAATAGCTTATGCGCATCAGACGAACACAGAACATGGATGCGTCCAGGGTCGACCCTCGGATCCGGAAGCAGGCGATTCTTATCGAGATGCTCCTCGAGTAAGCTGTTTTATAAAATTTCTGTGCCAAAATTATCGTTCCCTCGGCGTAAGATCAGAAGTCCAAAGCGCGACTCGGCGCACTAGAACATCTTGGGTCCCGTTAGGAGGCCCCATTCGTAACGTGGTGGCAAGCACCTTTGCCGGCTATAAGAACGGGAAGGCCGCACTGCGC'

s2 = reverse_complement(s1)
i=0
print s1, s2
while i <= (len(s1) - 4):
  j = 12
  while j >=4:
    if (j + i) < len(s1):
        if s1[i:i+j] in s2: 
          print i+1,j
          break
    j-=1
  i+=1
 

